# Generated by Django 4.0.4 on 2022-04-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('exchange', models.FloatField()),
            ],
            options={
                'verbose_name': 'ExchangeRate',
                'verbose_name_plural': 'ExchangeRates',
            },
        ),
    ]
