# Generated by Django 4.0.4 on 2022-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='exchange',
            new_name='purchase_price',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='sale_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
